### ISSUE TITLE
下载浏览器报错

### ISSUE THREAD

**Issue by hhls** [fanyong920/jvppeteer#10]
2020-08-07 16:37:30.091 [main] INFO  com.ruiyun.jvppeteer.core.browser.BrowserFetcher - Downloading binary from https://npm.taobao.org/mirrors/chromium-browser-snapshots/Mac/782078/chrome-mac.zip
2020-08-07 16:37:57.821 [main] ERROR com.ruiyun.jvppeteer.util.DownloadUtil - ProgressCallback has some problem
java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
	at java.math.BigDecimal.divide(BigDecimal.java:1690)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.lambda$defaultDownloadCallback$0(BrowserFetcher.java:274)
	at com.ruiyun.jvppeteer.util.DownloadUtil.download(DownloadUtil.java:107)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.downloadFile(BrowserFetcher.java:704)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.download(BrowserFetcher.java:235)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.download(BrowserFetcher.java:301)
	at com.bj58.zhaopin.qa.address.BossAddressTest.main(BossAddressTest.java:20)

**Comment by fanyong920** [comment]
已经修改了的。不过还没发布到maven

**Comment by fanyong920** [comment]
虽然我打印了报错信息，但是不影响下载使用
