### ISSUE TITLE
win64 下载其他版本chrome解压时出错

### ISSUE THREAD

**Issue by zw-95** [fanyong920/jvppeteer#122]
解压时读取不到文件夹，导致解压文件时报错找不到位置：
1000221版本
![image](https://user-images.githubusercontent.com/35022819/199385624-8e161afb-1567-4ec5-8bf2-48186656c905.png)

722234版本
![image](https://user-images.githubusercontent.com/35022819/199385798-d4b0c64a-7776-4878-b93b-09e166287206.png)

能否优化下解压逻辑

**Comment by zw-95** [comment]
补充：
## 测试html转pdf

测试代码：
```java
    public static void testPdf() throws InterruptedException, ExecutionException, IOException {

        //自动下载，第一次下载后不会再下载
//        BrowserFetcher.downloadIfNotExist(null);
        BrowserFetcher.downloadIfNotExist("1000221");
        ArrayList<String> arrayList = new ArrayList<>();
        //生成pdf必须在无厘头模式下才能生效
        LaunchOptions options = new LaunchOptionsBuilder().withArgs(arrayList).withHeadless(true).build();
        arrayList.add("--no-sandbox");
        arrayList.add("--disable-setuid-sandbox");
        Browser browser = Puppeteer.launch(options);
        Page page = browser.newPage();
        page.goTo("https://www.baidu.com");
        PDFOptions pdfOptions = new PDFOptions();
        pdfOptions.setPrintBackground(true);
        pdfOptions.setPreferCSSPageSize(true);
        pdfOptions.setPath("test.pdf");
        page.pdf(pdfOptions);
        page.close();
        browser.close();
    }
```
目录情况：
![image](https://user-images.githubusercontent.com/35022819/199386328-1a547e7f-31c5-41ab-8263-4d09496e5593.png)

报错：
``` java
Exception in thread "main" java.io.FileNotFoundException: D:\WorkDocument\Projects\C5\test\test\.local-browser\win64-1000221\chrome-win\mojo_core.dll (系统找不到指定的路径。)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.extractZip(BrowserFetcher.java:692)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.install(BrowserFetcher.java:487)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.download(BrowserFetcher.java:248)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.download(BrowserFetcher.java:274)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.downloadIfNotExist(BrowserFetcher.java:170)
	at org.example.Main.testPdf(Main.java:95)
	at org.example.Main.main(Main.java:45)
```

**Comment by liux1506** [comment]
高版本下载chrome出错。在解压时做个校验即可
```java
// BrowserFetcher.java line 685
private void extractZip(String archivePath, String folderPath) throws IOException {
        BufferedOutputStream wirter = null;
        BufferedInputStream reader = null;
        ZipFile zipFile = new ZipFile(archivePath);
        Enumeration<? extends ZipEntry> entries = zipFile.entries();
        try {
            while (entries.hasMoreElements()) {
                ZipEntry zipEntry = entries.nextElement();
                String name = zipEntry.getName();
                Path path = Paths.get(folderPath, name);
                if (zipEntry.isDirectory()) {
                    path.toFile().mkdirs();
                } else {
	                if (!Files.exists(path.getParent())) {
		                path.getParent().toFile().mkdirs();
	                }
                    try {
                        reader = new BufferedInputStream(zipFile.getInputStream(zipEntry));
                        int perReadcount;
                        byte[] buffer = new byte[Constant.DEFAULT_BUFFER_SIZE];
                        wirter = new BufferedOutputStream(new FileOutputStream(path.toString()));
                        while ((perReadcount = reader.read(buffer, 0, Constant.DEFAULT_BUFFER_SIZE)) != -1) {
                            wirter.write(buffer, 0, perReadcount);
                        }
                        wirter.flush();
                    }finally {
                        StreamUtil.closeQuietly(wirter);
                        StreamUtil.closeQuietly(reader);
                    }
                }
            }
        } finally {
            StreamUtil.closeQuietly(wirter);
            StreamUtil.closeQuietly(reader);
            StreamUtil.closeQuietly(zipFile);
        }
    }
```

@zw-95

**Comment by xiaomujin** [comment]
浏览器版本号：1361620
1.1.6 未修复

**Comment by fanyong920** [comment]
在2.0.0版本，采用shell 下载并解压，成功下载并解压高版本，在DownloadApi.Test有例子

**Comment by xiaomujin** [comment]
> 在2.0.0版本，采用shell 下载并解压，成功下载并解压高版本，在DownloadApi.Test有例子

老师接下来会持续维护更新这个项目吗

**Comment by fanyong920** [comment]
不一定，最近心血来潮，加上特别有空，所以有时间放在这方面，后面还得看有没有时间
