### ISSUE TITLE
下载浏览器时空指针异常

### ISSUE THREAD

**Issue by xiaoACE6716** [fanyong920/jvppeteer#133]
尝试使用时跑了一遍仓库给的DownloadChromiumExample，然而报错了
`Exception in thread "main" java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.parseRevision(BrowserFetcher.java:339)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.fetchRevision(BrowserFetcher.java:323)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.download(BrowserFetcher.java:313)
	at Test.main(Test.java:18)`

进调试看了眼是发现执行到parseRevision的时候正则没匹配到东西result为null，继续执行到下面的Objects.requireNonNull就爆了，望修复

**Comment by fanyong920** [comment]
ok,v2.0.0后修复
