### ISSUE TITLE
生成pdf有小概率报错：com.ruiyun.jvppeteer.exception.ProtocolException: Protocol error IO.read Target closed.

### ISSUE THREAD

**Issue by lewe518** [fanyong920/jvppeteer#151]
错误堆栈如下：
```
com.ruiyun.jvppeteer.exception.ProtocolException: Protocol error IO.read Target closed.
	at com.ruiyun.jvppeteer.transport.CDPSession.send(CDPSession.java:140)
	at com.ruiyun.jvppeteer.util.Helper.printPDF(Helper.java:257)
	at com.ruiyun.jvppeteer.util.Helper.readProtocolStream(Helper.java:228)
	at com.ruiyun.jvppeteer.core.page.Page.pdf(Page.java:1739)
```

版本信息：
```
<dependency>
    <groupId>io.github.fanyong920</groupId>
    <artifactId>jvppeteer</artifactId>
    <version>1.1.5</version>
</dependency>
```

**Comment by fanyong920** [comment]
2.2.3试试
