### ISSUE TITLE
部署到k8s的pod中，调用报错 Failed to launch the browser process:Cannot run program "/.local-browser/linux-722234/chrome-linux/chrome": error=2, No such file or directory

### ISSUE THREAD

**Issue by lianling121** [fanyong920/jvppeteer#153]
我服务是部署到K8S的pod里面的，然后前端通过接口执行页面加载，代码如下：
`
    public InputStream getQrCodeData(){

        try {
            if (page == null || page.isClosed()){
                //自动下载，第一次下载后不会再下载
                BrowserFetcher.downloadIfNotExist(null);
                ArrayList<String> argList = new ArrayList<>();
                // withHeadless 是否开启无头模式，无头模式不会显示浏览器
                LaunchOptions options = new LaunchOptionsBuilder().withArgs(argList).withHeadless(false).build();
                argList.add("--no-sandbox");
                argList.add("--disable-setuid-sandbox");
                Browser browser = Puppeteer.launch(options);
                page = browser.newPage();
            }
            page.goTo(WX_HOST);
            // 等待页面加载完成
            this.checkCookieHasName("uuid");
            Map<String,String> headers = this.getHeaders();
            this.asyncTaskExecutor.execute(() -> getScanLoginQrCode(headers));
            // 获取二维码
            String url = "https://mp.weixin.qq.com/cgi-bin/scanloginqrcode?action=getqrcode&random=" + System.currentTimeMillis();
            HttpResponse response = HttpClientUtil.httpResponseService(url, headers, null, HttpType.GET);
            return response.getEntity().getContent();
        }catch(Exception e){
            e.printStackTrace();
        }
        return null;
    }

`

执行Browser browser = Puppeteer.launch(options);报错
com.ruiyun.jvppeteer.exception.LaunchException: Failed to launch the browser process:Cannot run program "/.local-browser/linux-722234/chrome-linux/chrome": error=2, No such file or directory
	at com.ruiyun.jvppeteer.launch.ChromeLauncher.launch(ChromeLauncher.java:99)
2024-07-02T20:20:39.839601338+08:00 	at com.ruiyun.jvppeteer.core.Puppeteer.rawLaunch(Puppeteer.java:164)
	at com.ruiyun.jvppeteer.core.Puppeteer.launch(Puppeteer.java:65)
2024-07-02T20:20:39.839616298+08:00 	at com.seres.intelligenceplatform.services.client.api.WeChatApi.getQrCodeData(WeChatApi.java:88)
2024-07-02T20:20:39.839628284+08:00 	at com.seres.intelligenceplatform.services.application.v0.common.GetWxLoginQrCodeApplication.doServe(GetWxLoginQrCodeApplication.java:29)
	at com.seres.intelligenceplatform.services.application.v0.common.GetWxLoginQrCodeApplication.doServe(GetWxLoginQrCodeApplication.java:19)
2024-07-02T20:20:39.839634420+08:00 	at com.platform.sp.application.base.AbstractApplication.serve(AbstractApplication.java:53)
2024-07-02T20:20:39.839637214+08:00 	at com.platform.sp.application.base.TransactionalApplier.applyNoTransaction(TransactionalApplier.java:22)
2024-07-02T20:20:39.839650057+08:00 	at com.platform.sp.application.base.TransactionalApplier$$FastClassBySpringCGLIB$$b33671de.invoke(<generated>)
2024-07-02T20:20:39.839652614+08:00 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
2024-07-02T20:20:39.839657588+08:00 	at com.platform.sp.application.base.TransactionalApplier$$EnhancerBySpringCGLIB$$85cd9695.applyNoTransaction(<generated>)
2024-07-02T20:20:39.839660155+08:00 	at com.platform.sp.application.base.ApplicationDelegator.apply(ApplicationDelegator.java:17)
2024-07-02T20:20:39.839663034+08:00 	at com.seres.intelligenceplatform.services.facade.api.controller.v0.CommonController.getWxLoginQrCode$original$f1I9GpA3(CommonController.java:149)
2024-07-02T20:20:39.839666639+08:00 	at com.seres.intelligenceplatform.services.facade.api.controller.v0.CommonController.getWxLoginQrCode$original$f1I9GpA3$accessor$r7Xj7rZL(CommonController.java)
2024-07-02T20:20:39.839672578+08:00 	at com.seres.intelligenceplatform.services.facade.api.controller.v0.CommonController$auxiliary$tavsYFWr.call(Unknown Source)
2024-07-02T20:20:39.839694177+08:00 	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
2024-07-02T20:20:39.839697484+08:00 	at com.seres.intelligenceplatform.services.facade.api.controller.v0.CommonController.getWxLoginQrCode(CommonController.java)
2024-07-02T20:20:39.839700244+08:00 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-07-02T20:20:39.839703050+08:00 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-07-02T20:20:39.839705510+08:00 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-07-02T20:20:39.839707982+08:00 	at java.lang.reflect.Method.invoke(Method.java:498)
2024-07-02T20:20:39.839716558+08:00 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
2024-07-02T20:20:39.839719220+08:00 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
2024-07-02T20:20:39
.839721790+08:00 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
2024-07-02T20:20:39.839725542+08:00 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
2024-07-02T20:20:39.839727901+08:00 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
2024-07-02T20:20:39.839730263+08:00 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
2024-07-02T20:20:39.839732699+08:00 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
2024-07-02T20:20:39.839735026+08:00 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
2024-07-02T20:20:39.839737345+08:00 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
2024-07-02T20:20:39.839739726+08:00 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
2024-07-02T20:20:39.839744241+08:00 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
2024-07-02T20:20:39.839747230+08:00 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
2024-07-02T20:20:39.839749602+08:00 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
2024-07-02T20:20:39.839764147+08:00 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
2024-07-02T20:20:39.839766535+08:00 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-02T20:20:39.839769995+08:00 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
2024-07-02T20:20:39.839772384+08:00 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2024-07-02T20:20
:39.839774792+08:00 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-02T20:20:39.839777126+08:00 	at com.github.xiaoymin.swaggerbootstrapui.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:81)
2024-07-02T20:20:39.839783039+08:00 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2024-07-02T20:20:39.839785460+08:00 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-02T20:20:39.839787859+08:00 	at com.github.xiaoymin.swaggerbootstrapui.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)
2024-07-02T20:20:39.839790140+08:00 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2024-07-02T20:20:39.839792500+08:00 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-02T20:20:39.839794907+08:00 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
2024-07-02T20:20:39.839797319+08:00 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2024-07-02T20:20:39.839799664+08:00 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2024-07-02T20:20:39.839802023+08:00 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-02T20:20:39.839808630+08:00 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
2024-07-02T20:20:39.839814306+08:00 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
2024-07-02T20:20:39.839816667+08:00 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2024-07-02T20:20:39.839819198+08:00 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-02T20:20:39
.839823021+08:00 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:97)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
2024-07-02T20:20:39.840376431+08:00 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-02T20:20:39.840378954+08:00 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
2024-07-02T20:20:39.840381343+08:00 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
2024-07-02T20:20:39.840388333+08:00 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
2024-07-02T20:20:39.840395004+08:00 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
2024-07-02T20:20:39.840399551+08:00 	at org.apache.catalina.core.StandardHostValve.invoke$original$SB1cSYu8(StandardHostValve.java:143)
	at org.apache.catalina.core.StandardHostValve.invoke$original$SB1cSYu8$accessor$cGkI2xMG(StandardHostValve.java)
2024-07-02T20:20:39.840404374+08:00 	at org.apache.catalina.core.StandardHostValve$auxiliary$BDPabWCY.call(Unknown Source)
2024-07-02T20:20:39.840406664+08:00 	at org.apache.skywalking.apm.agent.core.plugin.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:86)
2024-07-02T20:20:39.840409141+08:00 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java)
2024-07-02T20:20:39.840411459+08:00 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
2024-07-02T20:20:39.840413628+08:00 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
2024-07-02T20:20:39.840421042+08:00 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
2024-07-02T20:20:39.840428041+08:00 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
2024-07-02T20:20:39.840430247+08:00 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2024-07-02T20:20:39.840432569+08:00 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2024-07-02T20:20:39.840434910+08:00 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2024-07-02T20:20:39.840440877+08:00 	at java.lang.Thread.run(Thread.java:750)
2024-07-02T20:20:39.840443341+08:00 Caused by: java.io.IOException: Cannot run program "/.local-browser/linux-722234/chrome-linux/chrome": error=2, No such file or directory
2024-07-02T20:20:39.840445914+08:00 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
2024-07-02T20:20:39.840448478+08:00 	at com.ruiyun.jvppeteer.core.browser.BrowserRunner.start(BrowserRunner.java:84)
2024-07-02T20:20:39.840450920+08:00 	at com.ruiyun.jvppeteer.launch.ChromeLauncher.launch(ChromeLauncher.java:88)
2024-07-02T20:20:39.840453291+08:00 	... 82 more
2024-07-02T20:20:39.840458395+08:00 Caused by: java.io.IOException: error=2, No such file or directory
2024-07-02T20:20:39.840460850+08:00 	at java.lang.UNIXProcess.forkAndExec(Native Method)
2024-07-02T20:20:39.840463228+08:00 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
2024-07-02T20:20:39.840465505+08:00 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
2024-07-02T20:20:39.840467905+08:00 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
2024-07-02T20:20:39.840470286+08:00 	... 84 more

求大佬看看怎么搞呢

**Comment by lianling121** [comment]
查看对应目录：/.local-browser/linux-722234/chrome-linux/chrome 是有该文件的

**Comment by fanyong920** [comment]
/.local-browser/linux-722234/chrome-linux/chrome  /开头是系统根目录，不是项目根目录，路径不对。

**Comment by fanyong920** [comment]
System.getProperty("user.dir")有时候不起作用，导致获取的路径不对，这时候你可以LaunchOptions里Cache参数里设置缓存目录
