### ISSUE TITLE
linux指定ExecutablePath还是不指定，都会报错，c.r.j.transport.WebSocketTransport - Connection closed by remote peer Code: -1

### ISSUE THREAD

**Issue by PiZhai** [fanyong920/jvppeteer#155]
```
    @SneakyThrows
    public static void test(String htmlPath) {
        //自动下载，第一次下载后不会再下载
//        BrowserFetcher.downloadIfNotExist("1360176");
//        BrowserFetcher.downloadIfNotExist("1358622");
        ArrayList<String> arrayList = new ArrayList<>();
        //生成pdf必须在无厘头模式下才能生效
//        LaunchOptions options = new LaunchOptionsBuilder().withExecutablePath("/usr/local/chrome-linux64/chrome").withArgs(arrayList).withHeadless(true).build();
        LaunchOptions options = new LaunchOptionsBuilder()
                .withExecutablePath("/usr/bin/google-chrome")
                .withArgs(arrayList).withHeadless(true).build();
        arrayList.add("--no-sandbox");
        arrayList.add("--disable-setuid-sandbox");
        arrayList.add("--disable-gpu");
        Browser browser = Puppeteer.launch(options);
        Page page = browser.newPage();
//        page.goTo("https://www.baidu.com/?tn=98012088_10_dg&ch=3");
        page.goTo("file:///" + htmlPath);
        PDFOptions pdfOptions = new PDFOptions();
//        pdfOptions.setHeight("297mm");
//        pdfOptions.setWidth("420mm");
        pdfOptions.setPrintBackground(true);
        pdfOptions.setPreferCSSPageSize(true);
        pdfOptions.setPath("/opt/projects/onlineexam/end/answersheet/298.pdf");
        page.pdf(pdfOptions);
        page.close();
        browser.close();
    }
```

报错：

```
2024-09-27 15:17:51 [WebSocketConnectReadThread-198] INFO  c.r.j.transport.WebSocketTransport - Connection closed by remote peer Code: -1 Reason: 
2024-09-27 15:17:51 [WebSocketConnectReadThread-198] ERROR c.r.j.transport.WebSocketTransport - Websocket error:
java.lang.NullPointerException: Cannot invoke "com.ruiyun.jvppeteer.transport.Connection.dispose()" because "this.connection" is null
	at com.ruiyun.jvppeteer.transport.WebSocketTransport.onClose(WebSocketTransport.java:84) ~[jvppeteer-1.1.6.jar!/:na]
	at org.java_websocket.client.WebSocketClient.onWebsocketClose(WebSocketClient.java:617) ~[Java-WebSocket-1.5.0.jar!/:na]
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:522) ~[Java-WebSocket-1.5.0.jar!/:na]
	at org.java_websocket.WebSocketImpl.closeConnection(WebSocketImpl.java:534) ~[Java-WebSocket-1.5.0.jar!/:na]
	at org.java_websocket.WebSocketImpl.eot(WebSocketImpl.java:572) ~[Java-WebSocket-1.5.0.jar!/:na]
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:510) ~[Java-WebSocket-1.5.0.jar!/:na]
	at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]
```

**Comment by fanyong920** [comment]
*     1000 = 正常关闭
     *     1001 = 终端离开, 可能因为服务端错误, 也可能因为浏览器正从打开连接的页面跳转离开
     *     1002 = 由于协议错误而中断连接
     *     1003 = 由于接收到不允许的数据类型而断开连接 (如仅接收文本数据的终端接收到了二进制数据)
     *     1005 = 表示没有收到预期的状态码
     *     1006 = 用于期望收到状态码时连接非正常关闭 (也就是说, 没有发送关闭帧)
     *     1007 = 由于收到了格式不符的数据而断开连接 (如文本消息中包含了非 UTF-8 数据)
     *     1008 = 由于收到不符合约定的数据而断开连接。 这是一个通用状态码, 用于不适合使用 1003 和 1009 状态码的场景
     *     1009 = 由于收到过大的数据帧而断开连接
     *     1010 = 客户端期望服务器商定一个或多个拓展, 但服务器没有处理, 因此客户端断开连接
     *     1011 = 客户端由于遇到没有预料的情况阻止其完成请求, 因此服务端断开连接。
     *     1012 = 服务器由于重启而断开连接。 这是一个通用状态码, 用于不适合使用 1001 状态码的场景
     *     1013 = 服务器由于临时原因断开连接, 如服务器过载因此断开一部分客户端连接
     *     1015 = 表示连接由于无法完成 TLS 握手而关闭 (例如无法验证服务器证书)
     *     -1 = 表示连接尚未打开
     *     -2 = 表示连接由于内部错误而关闭
     *     -3 = 表示连接由于无法完成 flash 策略检查而关闭

**Comment by PiZhai** [comment]
请问为什么没有连接呢？

**Comment by fanyong920** [comment]
我不知道，具体看linux环境
