### ISSUE TITLE
点击下载文件按钮后再次使用Page 的 $ 等方法都hang住了

### ISSUE THREAD

**Issue by zhonglh** [fanyong920/jvppeteer#158]
通过 Page 的 $方法取到了下载文件对应的div , 调用 click 后， 文件能正常下载， 但是 下载后 再操作  ， 比如 click 或者  Page.$ 都hang 住了， 一直卡死了 ， 过了几分钟后 显示异常：
java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.TimeoutException: The source did not signal an event for 180000 milliseconds and has been terminated.
	at com.ruiyun.jvppeteer.core.page.ExecutionContext.evaluateInternal(ExecutionContext.java:119)
	at com.ruiyun.jvppeteer.core.page.ExecutionContext.evaluate(ExecutionContext.java:69)
	at com.ruiyun.jvppeteer.core.page.JSHandle.evaluate(JSHandle.java:43)
	at com.ruiyun.jvppeteer.core.page.ElementHandle.scrollIntoViewIfNeeded(ElementHandle.java:98)
	at com.ruiyun.jvppeteer.core.page.ElementHandle.click(ElementHandle.java:343)
	at com.ruiyun.jvppeteer.core.page.ElementHandle.click(ElementHandle.java:329)

**Comment by fanyong920** [comment]
给个demo
