### ISSUE TITLE
当设置--user-data-dir参数后，会报错Can't get WSEndpoint

### ISSUE THREAD

**Issue by coolguitar** [fanyong920/jvppeteer#164]
版本：2.2.1，错误信息如下：
------------------------------------错误信息-------------------------------------------
Exception in thread "main" com.ruiyun.jvppeteer.exception.LaunchException: Can't get WSEndpoint
	at com.ruiyun.jvppeteer.core.BrowserRunner$StreamReader.getResult(BrowserRunner.java:205)
	at com.ruiyun.jvppeteer.core.BrowserRunner.waitForWSEndpoint(BrowserRunner.java:220)
	at com.ruiyun.jvppeteer.core.BrowserRunner.setUpConnection(BrowserRunner.java:153)
	at com.ruiyun.jvppeteer.launch.BrowserLauncher.run(BrowserLauncher.java:137)
	at com.ruiyun.jvppeteer.launch.ChromeLauncher.launch(ChromeLauncher.java:58)
	at com.ruiyun.jvppeteer.core.Puppeteer.rawLaunch(Puppeteer.java:83)
	at com.ruiyun.jvppeteer.core.Puppeteer.launch(Puppeteer.java:62)
	at dev.greenday.contactus.ContactusPageRobot.testLoginLive(ContactusPageRobot.java:560)
	at dev.greenday.contactus.ContactusPageRobot.main(ContactusPageRobot.java:657)
----------------------------------debug发现有乱码如下-------------------------------------------
<img width="1004" alt="1731595041898" src="https://github.com/user-attachments/assets/97a78c13-d39d-4b26-8a81-c08b01a114a1">

**Comment by fanyong920** [comment]
—user-data-dir=xxxxx，xxx是一个目录，是这样设置吗

**Comment by coolguitar** [comment]
是这样设置的，--user-data-dir=D:\data\chrome

**Comment by Yamcanda** [comment]
同样的问题，Linux 下设不设置都是报错，换不同浏览器版本也是一样。

**Comment by fanyong920** [comment]
把报错原因打印出来看看

**Comment by fanyong920** [comment]
把代码放上来

**Comment by Yamcanda** [comment]
版本：2.2.1, 2.2.0, 2.1.2,  linux debian 12 chrome: 131, 118, 错误信息如下：
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
Exception in thread "main" com.ruiyun.jvppeteer.exception.LaunchException: Can't get WSEndpoint
	at com.ruiyun.jvppeteer.core.BrowserRunner$StreamReader.getResult(BrowserRunner.java:205)
	at com.ruiyun.jvppeteer.core.BrowserRunner.waitForWSEndpoint(BrowserRunner.java:220)
	at com.ruiyun.jvppeteer.core.BrowserRunner.setUpConnection(BrowserRunner.java:153)
	at com.ruiyun.jvppeteer.launch.ChromeLauncher.launch(ChromeLauncher.java:94)
	at com.ruiyun.jvppeteer.core.Puppeteer.rawLaunch(Puppeteer.java:82)
	at com.ruiyun.jvppeteer.core.Puppeteer.launch(Puppeteer.java:61)
	at com.ruiyun.example.TestSnap.main(TestSnap.java:34)

**Comment by fanyong920** [comment]
实现一下日志，日志会打印具体信息，现在浏览器输出得错误信息

**Comment by fanyong920** [comment]
实现一下日志，日志会打印具体信息，现在看不到浏览器输出得错误信息

**Comment by fanyong920** [comment]
或者设dumpio =true

**Comment by coolguitar** [comment]
> ```java
>   launchOptions.setArgs(Collections.singletonList("--user-data-dir=D:\\data\\chrome"));
> ```

我是这样设置的，如果加了这个user-data-dir参数，启动就会报“Can't get WSEndpoint”错误，如果把这行注释掉，就可以正常打开页面。

**Comment by coolguitar** [comment]
> > ```java
> >   launchOptions.setArgs(Collections.singletonList("--user-data-dir=D:\\data\\chrome"));
> > ```
> 
> 我是这样设置的，如果加了这个user-data-dir参数，启动就会报“Can't get WSEndpoint”错误，如果把这行注释掉，就可以正常打开页面。

增加配置如下：
<img width="814" alt="1731649023055" src="https://github.com/user-attachments/assets/799356a2-aa5a-4173-80f5-0d7402fd365a">

去掉配置如下：
![image](https://github.com/user-attachments/assets/53b34886-a602-4dd8-8e14-604edbdc668d)

**Comment by fanyong920** [comment]
```java
launchOptions.setDumpio(true);
```
加上这个配置，我才能看到真正得错误。

**Comment by coolguitar** [comment]
加上后打印的乱码，和debug里面看到的似乎一样。

![image](https://github.com/user-attachments/assets/a6f30ee8-d442-482f-8a10-3a9cf55e1361)

**Comment by coolguitar** [comment]
改变字符集，乱码显示如下

![image](https://github.com/user-attachments/assets/bbbdb33b-27ae-47d2-8d94-3b7b47ecbfd1)

**Comment by fanyong920** [comment]
好的，周一见

**Comment by fanyong920** [comment]
试试2.2.0

**Comment by fanyong920** [comment]
2.2.2 试试

**Comment by coolguitar** [comment]
用了2.2.2，浏览器没有导航到目标地址，日志信息如下：

[main] INFO com.ruiyun.jvppeteer.core.BrowserFetcher - revision:130.0.6723.58, executablePath:D:\work\eclipse-workspace\green\.local-browser\win64-130.0.6723.58\chrome-win64\chrome.exe, folderPath:D:\work\eclipse-workspace\green\.local-browser\win64-130.0.6723.58, local:true, url:http://storage.googleapis.com/chrome-for-testing-public/130.0.6723.58/win64/chrome-win64.zip, product:CHROME
2024-11-18 16:42:36,336 [dev.greenday.contactus.ContactusPageRobot]-[INFO] download browser finish,cost:46

[14120:12940:1118/164237.054:ERROR:sandbox_win.cc(852)] Sandbox cannot access executable. Check filesystem permissions are valid. See https://bit.ly/31yqMJR.: 拒绝访问。 (0x5)

DevTools listening on ws://127.0.0.1:52225/devtools/browser/5186ec3f-bfdd-40aa-b241-90cdd415071a
[WebSocketConnectReadThread-14] INFO com.ruiyun.jvppeteer.transport.WebSocketTransport - Websocket serverHandshake status: 101
2024-11-18 16:42:38,418 [dev.greenday.contactus.ContactusPageRobot]-[INFO] -----Puppeteer.launch cost:2081 ms.
2024-11-18 16:42:38,419 [dev.greenday.contactus.ContactusPageRobot]-[INFO] -----init end.
正在现有的浏览器会话中打开。

**Comment by coolguitar** [comment]
> 用了2.2.2，浏览器没有导航到目标地址，日志信息如下：
> 
> [main] INFO com.ruiyun.jvppeteer.core.BrowserFetcher - revision:130.0.6723.58, executablePath:D:\work\eclipse-workspace\green.local-browser\win64-130.0.6723.58\chrome-win64\chrome.exe, folderPath:D:\work\eclipse-workspace\green.local-browser\win64-130.0.6723.58, local:true, url:http://storage.googleapis.com/chrome-for-testing-public/130.0.6723.58/win64/chrome-win64.zip, product:CHROME 2024-11-18 16:42:36,336 [dev.greenday.contactus.ContactusPageRobot]-[INFO] download browser finish,cost:46
> 
> [14120:12940:1118/164237.054:ERROR:sandbox_win.cc(852)] Sandbox cannot access executable. Check filesystem permissions are valid. See https://bit.ly/31yqMJR.: 拒绝访问。 (0x5)
> 
> DevTools listening on ws://127.0.0.1:52225/devtools/browser/5186ec3f-bfdd-40aa-b241-90cdd415071a [WebSocketConnectReadThread-14] INFO com.ruiyun.jvppeteer.transport.WebSocketTransport - Websocket serverHandshake status: 101 2024-11-18 16:42:38,418 [dev.greenday.contactus.ContactusPageRobot]-[INFO] -----Puppeteer.launch cost:2081 ms. 2024-11-18 16:42:38,419 [dev.greenday.contactus.ContactusPageRobot]-[INFO] -----init end. 正在现有的浏览器会话中打开。

日志信息没贴全，补充全部如下：



[main] INFO com.ruiyun.jvppeteer.core.BrowserFetcher - revision:130.0.6723.58, executablePath:D:\work\eclipse-workspace\green\.local-browser\win64-130.0.6723.58\chrome-win64\chrome.exe, folderPath:D:\work\eclipse-workspace\green\.local-browser\win64-130.0.6723.58, local:true, url:http://storage.googleapis.com/chrome-for-testing-public/130.0.6723.58/win64/chrome-win64.zip, product:CHROME
2024-11-18 16:48:43,510 [dev.greenday.contactus.ContactusPageRobot]-[INFO] download browser finish,cost:40
[13240:22312:1118/164844.207:ERROR:sandbox_win.cc(852)] Sandbox cannot access executable. Check filesystem permissions are valid. See https://bit.ly/31yqMJR.: 鎷掔粷璁块棶銆? (0x5)

DevTools listening on ws://127.0.0.1:61967/devtools/browser/39664968-c00a-45e7-9d7b-bf3e0d8466ab
[WebSocketConnectReadThread-14] INFO com.ruiyun.jvppeteer.transport.WebSocketTransport - Websocket serverHandshake status: 101
2024-11-18 16:48:45,466 [dev.greenday.contactus.ContactusPageRobot]-[INFO] -----Puppeteer.launch cost:1955 ms.
2024-11-18 16:48:45,467 [dev.greenday.contactus.ContactusPageRobot]-[INFO] -----init end.
正在现有的浏览器会话中打开。
Exception in thread "main" com.ruiyun.jvppeteer.exception.TimeoutException: Failed to launch the browser process!Chrome output: 正在现有的浏览器会话中打开。
	at com.ruiyun.jvppeteer.core.BrowserRunner$StreamReader.waitFor(BrowserRunner.java:211)
	at com.ruiyun.jvppeteer.core.BrowserRunner.waitForWSEndpoint(BrowserRunner.java:230)
	at com.ruiyun.jvppeteer.core.BrowserRunner.setUpConnection(BrowserRunner.java:154)
	at com.ruiyun.jvppeteer.launch.BrowserLauncher.run(BrowserLauncher.java:137)
	at com.ruiyun.jvppeteer.launch.ChromeLauncher.launch(ChromeLauncher.java:59)
	at com.ruiyun.jvppeteer.core.Puppeteer.rawLaunch(Puppeteer.java:83)
	at com.ruiyun.jvppeteer.core.Puppeteer.launch(Puppeteer.java:62)
	at dev.greenday.contactus.ContactusPageRobot.testReopenLive(ContactusPageRobot.java:600)
	at dev.greenday.contactus.ContactusPageRobot.main(ContactusPageRobot.java:640)

**Comment by fanyong920** [comment]
```java
ArrayList<String> args = new ArrayList<>();//添加一些额外的启动参数
        args.add("--no-sandbox");
        launchOptions.setArgs(args);
```
添加这个参数

**Comment by fanyong920** [comment]
还有把任务管理器里已经启动的chrome for testing 全部杀死，再重新测试

**Comment by fanyong920** [comment]
[aliapp.log](https://github.com/user-attachments/files/17798144/aliapp.log)

**Comment by coolguitar** [comment]
[chrome.zip](https://github.com/user-attachments/files/17800432/chrome.zip)

user-data-dir压缩如附件

**Comment by fanyong920** [comment]
我jdk8测试一直没问题

**Comment by coolguitar** [comment]
可以把你的测试代码发一下吗，谢谢

**Comment by fanyong920** [comment]
```java

 public final LaunchOptions launchOptions = LaunchOptions.builder().executablePath("C:\\Users\\fanyong\\Desktop\\jvppeteer\\example\\.local-browser\\win32-130.0.6723.58\\chrome-win32\\chrome.exe").headless(true).build();

    /**
     * 手动配置路径来启动浏览器
     * 优先级： 1 高
     */
    @Test
    public void test99() throws IOException {
//        launchOptions.setExecutablePath("C:\\Users\\fanyong\\Desktop\\jvppeteer\\example\\.local-browser\\win64-128.0.6613.137\\chrome-win64\\chrome.exe");
        launchOptions.setUserDataDir("C:\\Users\\fanyong\\Desktop\\chrome\\chrome");

        launchOptions.setArgs(getLaunchArguments());
        try (Browser browser = getBrowser()) {
            //打开一个页面
            Page page = browser.newPage();
            page.goTo("https://www.baidu.com/?tn=68018901_16_pg");
            Target target1 = page.target();
            System.out.println("one type=" + target1.type() + ", url=" + target1.url() + ",id=" + target1.getTargetId());
            List<Target> targets = browser.targets();
            //看看targets里面都有什么，包含browser,page,等类型,其中还包含了上面newPage得到page
            for (Target target : targets) {
                System.out.println("two type=" + target.type() + ", url=" + target.url() + ",id=" + target.getTargetId());
            }
        }
    }
    private static ArrayList<String> getLaunchArguments() {
        ArrayList<String> argList = new ArrayList<>();
        argList.add("--no-sandbox");
        argList.add("--disable-setuid-sandbox");
        //argList.add("--disable-blink-features=AutomationControlled");
        //argList.add("--auto-open-devtools-for-tabs");
        argList.add("--disable-infobars");
        //argList.add("--enable-webgl");
        //argList.add("--use-gl=swiftshader");
        argList.add("--disable-dev-shm-usage");
        argList.add("--lang=zh-CN");
        argList.add("--start-maximized");
        //设置插件
        return argList;
    }
```

**Comment by fanyong920** [comment]
用v2.2.3

**Comment by coolguitar** [comment]
用2.2.3和上面测试代码依然不正常，请问Java-WebSocket应该用哪个版本？我使用的是1.5.7

**Comment by fanyong920** [comment]
用1.5.7
我想不明白，根据你打印的日志，程序已经跑到建立websocket链接的步骤了，为啥在这之前的wsendpoint还在抛异常

**Comment by fanyong920** [comment]
用一个新的文件夹作为user dir多次测试看看

**Comment by fanyong920** [comment]
[2.2.4.zip](https://github.com/user-attachments/files/17808643/2.2.4.zip)
解压，放到maven的repository,manve引用2.2.4的jvppeteer。
我加了一句代码，把process.getOuputStream关闭了，看看程序还会不会返回跑

**Comment by coolguitar** [comment]
用2.2.4，然后不断的切换user-data-dir，还是超时抛错误：

正在现有的浏览器会话中打开。
Exception in thread "main" com.ruiyun.jvppeteer.exception.TimeoutException: Failed to launch the browser process!Chrome output: 正在现有的浏览器会话中打开。
	at com.ruiyun.jvppeteer.core.BrowserRunner$StreamReader.waitFor(BrowserRunner.java:211)
	at com.ruiyun.jvppeteer.core.BrowserRunner.waitForWSEndpoint(BrowserRunner.java:228)
	at com.ruiyun.jvppeteer.core.BrowserRunner.setUpConnection(BrowserRunner.java:154)
	at com.ruiyun.jvppeteer.launch.BrowserLauncher.run(BrowserLauncher.java:137)
	at com.ruiyun.jvppeteer.launch.ChromeLauncher.launch(ChromeLauncher.java:59)
	at com.ruiyun.jvppeteer.core.Puppeteer.rawLaunch(Puppeteer.java:83)
	at com.ruiyun.jvppeteer.core.Puppeteer.launch(Puppeteer.java:62)
	at dev.greenday.contactus.ContactusPageRobot.testReopenLive(ContactusPageRobot.java:598)
	at dev.greenday.contactus.ContactusPageRobot.main(ContactusPageRobot.java:636)

**Comment by coolguitar** [comment]
貌似可以了，我再试试

**Comment by coolguitar** [comment]
用2.2.3也可以了，问题产生的原因应该是在一个进程中创建了2个browser实例，这2个实例都用同一个usr-data-dir，就出现这个问题了。感谢这几天的debug帮助：）

**Comment by fanyong920** [comment]
好的
