### ISSUE TITLE
com.fasterxml.jackson.databind.exc.MismatchedInputException通过url生成pdf报错，但是pdf生成成功

### ISSUE THREAD

**Issue by 17853485317** [fanyong920/jvppeteer#166]
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.ruiyun.jvppeteer.entities.CookiePartitionKey` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('https://www.baidu.com/')
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: com.ruiyun.jvppeteer.events.ResponseReceivedExtraInfoEvent["cookiePartitionKey"])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1728)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1353)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1495)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:197)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4650)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2831)
        at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3295)
        at com.ruiyun.jvppeteer.transport.CDPSession.onMessage(CDPSession.java:130)
        at com.ruiyun.jvppeteer.transport.Connection.lambda$startHandleMessageThread$0(Connection.java:125)
        at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by fanyong920** [comment]
目前最好使用 chrome for testing 的 130.0.6723.58 版本。
不同版本对应不同版本的chrome devtool protocol协议。
协议不同，序列化旧出错
