### ISSUE TITLE
关于java.lang.IllegalArgumentException: Protocol error: Connection closed

### ISSUE THREAD

**Issue by coolguitar** [fanyong920/jvppeteer#167]
我是创建一个browser多次复用，这个browser new大概1000多个page的时候就会出这个异常。请问是我的用法不对，还是哪里有问题？，异常信息如下：

java.lang.IllegalArgumentException: Protocol error: Connection closed.
        at com.ruiyun.jvppeteer.util.ValidateUtil.assertArg(ValidateUtil.java:46)
        at com.ruiyun.jvppeteer.transport.Connection.rawSend(Connection.java:178)
        at com.ruiyun.jvppeteer.transport.Connection.send(Connection.java:169)
        at com.ruiyun.jvppeteer.core.Browser.createPageInContext(Browser.java:297)
        at com.ruiyun.jvppeteer.core.BrowserContext.newPage(BrowserContext.java:125)
        at com.ruiyun.jvppeteer.core.Browser.newPage(Browser.java:288)

**Comment by fanyong920** [comment]
你现在使用哪个版本的jvppeteer

**Comment by coolguitar** [comment]
版本：2.2.3
OS：centos 7

**Comment by fanyong920** [comment]
2.2.3 websocket已经有心跳机制的。connetion close时候打印有一条日志，你看看显示什么？你new的page应该不存在长时间搁置的情况吧

**Comment by coolguitar** [comment]
page创建后马上使用，然后就会关闭page，下面的日志就是心跳的吧？


2024-11-27 00:54:07.605  INFO 32515 --- [ctReadThread-30] c.r.j.transport.WebSocketTransport       : Connection closed by remote peer Code: 1006 Reason:
 Connection is abnormally closed without sending a close frame when expecting a status code
2024-11-27 00:56:19.032 ERROR 32515 --- [MessageThread-1] c.ruiyun.jvppeteer.events.EventEmitter   : jvppeteer error

com.ruiyun.jvppeteer.exception.TimeoutException: Timeout waiting for response for Page.addScriptToEvaluateOnNewDocument
        at com.ruiyun.jvppeteer.transport.Callback.waitForResponse(Callback.java:53) ~[jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.transport.CallbackRegistry.create(CallbackRegistry.java:34) ~[jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.transport.Connection.rawSend(Connection.java:183) ~[jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.transport.CDPSession.send(CDPSession.java:85) ~[jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.transport.CDPSession.send(CDPSession.java:78) ~[jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.core.FrameManager.createIsolatedWorld(FrameManager.java:397) ~[jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.core.FrameManager.initialize(FrameManager.java:198) ~[jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.core.FrameManager.onAttachedToTarget(FrameManager.java:289) ~[jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.core.Page.lambda$new$6(Page.java:293) ~[jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.core.Page$3.lambda$new$0(Page.java:259) ~[jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.events.EventEmitter.emit(EventEmitter.java:80) ~[jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.core.ChromeTargetManager.onAttachedToTarget(ChromeTargetManager.java:254) [jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.core.ChromeTargetManager.lambda$setupAttachmentListeners$2(ChromeTargetManager.java:313) [jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.events.EventEmitter.emit(EventEmitter.java:80) ~[jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.transport.CDPSession.onMessage(CDPSession.java:130) ~[jvppeteer-2.2.3.jar:na]
        at com.ruiyun.jvppeteer.transport.Connection.lambda$handleMessageRunnable$1(Connection.java:117) ~[jvppeteer-2.2.3.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_221]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_221]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_221]

**Comment by coolguitar** [comment]
连接是browser级别对吧，一个browser只会创建一个连接。我晚点用2.2.5试试。

**Comment by fanyong920** [comment]
发生错误后，服务器的浏览器进程还存在吗

**Comment by fanyong920** [comment]
是的，一个browser一个连接

**Comment by coolguitar** [comment]
> 发生错误后，服务器的浏览器进程还存在吗

进程还在，因为我把异常catch住了，继续new新的page

**Comment by fanyong920** [comment]
那应该是连接自动断了，用2.2.5估计也是一样的。我看看有没有办法一直保持连接

**Comment by fanyong920** [comment]
不过2.2.5可以打印心跳日志，有助于帮助解决问题

**Comment by coolguitar** [comment]
好的，我在用2.2.5试试

**Comment by fanyong920** [comment]
考虑使用netty实现websocket连接才行，netty稳如老狗

**Comment by coolguitar** [comment]
[trace-1128.log](https://github.com/user-attachments/files/17944799/trace-1128.log)
使用2.2.5重现的错误，trace log请参考附件。

**Comment by coolguitar** [comment]
> 考虑使用netty实现websocket连接才行，netty稳如老狗

感觉如果识别到连接到了，抛一个明确的异常出来给业务应用，由业务应用重新初始化browser也行。我打算这么实现。

**Comment by coolguitar** [comment]
> > 考虑使用netty实现websocket连接才行，netty稳如老狗
> 
> 感觉如果识别到连接到了，抛一个明确的异常出来给业务应用，由业务应用重新初始化browser也行。我打算这么实现。

或者暴漏一个监听连接断的callback给业务应用

**Comment by fanyong920** [comment]
```java
 cdpBrowser.on(BrowserEvents.Disconnected, target -> System.out.println("disconnected: "));
```
监听 Browser 的 Disconnected事件

**Comment by coolguitar** [comment]
试过了，监听到了BrowserEvents.Disconnected事件，连接断开后重新创建browser，程序跑的很稳定。感谢！
