### ISSUE TITLE
无痕模式下localStorage无法操作怎么办

### ISSUE THREAD

**Issue by besodata** [fanyong920/jvppeteer#170]
localStorage.setItem报无权限，但1.1.5版本下可以呢

**Comment by fanyong920** [comment]
```java
browserContext.overridePermissions("https://www.baidu.com", WebPermission.PERSISTENT_STORAGE);
```
试一下，授予持久化权限

**Comment by besodata** [comment]
passPage.browserContext().overridePermissions("https://www.baidu.com", WebPermission.PERSISTENT_STORAGE);
还是会报错
com.ruiyun.jvppeteer.exception.EvaluateException: DOMException : Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    jvppeteer print: at com.ruiyun.jvppeteer.core.Page.evaluate(Page.java:2097)
	at com.ruiyun.jvppeteer.util.Helper.createEvaluationError(Helper.java:154) ~[jvppeteer-2.2.5.jar:na]
	at com.ruiyun.jvppeteer.core.ExecutionContext.evaluateInternal(ExecutionContext.java:342) ~[jvppeteer-2.2.5.jar:na]
	at com.ruiyun.jvppeteer.core.ExecutionContext.evaluate(ExecutionContext.java:237) ~[jvppeteer-2.2.5.jar:na]
	at com.ruiyun.jvppeteer.core.IsolatedWorld.evaluate(IsolatedWorld.java:158) ~[jvppeteer-2.2.5.jar:na]
	at com.ruiyun.jvppeteer.core.Frame.evaluate(Frame.java:622) ~[jvppeteer-2.2.5.jar:na]
	at com.ruiyun.jvppeteer.core.Frame.evaluate(Frame.java:630) ~[jvppeteer-2.2.5.jar:na]
	at com.ruiyun.jvppeteer.core.Page.evaluate(Page.java:2111) ~[jvppeteer-2.2.5.jar:na]
	at com.ruiyun.jvppeteer.core.Page.evaluate(Page.java:2097) ~[jvppeteer-2.2.5.jar:na]

**Comment by fanyong920** [comment]
看一下，能重现问题的代码
