### ISSUE TITLE
下载指定版本的CHROMIUM失败

### ISSUE THREAD

**Issue by besodata** [fanyong920/jvppeteer#181]
//下载指定版本的CHROMIUM
        FetcherOptions fetcherOptions3 = new FetcherOptions();
        fetcherOptions3.setProduct(Product.Chromium);
        fetcherOptions3.setVersion("1366415");
        RevisionInfo revisionInfo5 = Puppeteer.downloadBrowser(fetcherOptions3);
        System.out.println("revisionInfo5: " + revisionInfo5);

java.lang.NumberFormatException: For input string: "131.0.6778.87"

	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at com.ruiyun.jvppeteer.cdp.core.BrowserFetcher.archive(BrowserFetcher.java:725)
	at com.ruiyun.jvppeteer.cdp.core.BrowserFetcher.relativeExecutablePath(BrowserFetcher.java:656)
	at com.ruiyun.jvppeteer.cdp.core.BrowserFetcher.revisionInfo(BrowserFetcher.java:623)
	at com.ruiyun.jvppeteer.cdp.core.BrowserFetcher.downloadBrowser(BrowserFetcher.java:299)
	at com.ruiyun.jvppeteer.cdp.core.Puppeteer.downloadBrowser(Puppeteer.java:186)
	at com.ruiyun.example.V_DownloadApiTest.test3(V_DownloadApiTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)

**Comment by fanyong920** [comment]
安排，3.1.3
