### ISSUE TITLE
1.0.9版本快速启动报NFE

### ISSUE THREAD

**Issue by Burgges** [fanyong920/jvppeteer#19]
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.archiveName(BrowserFetcher.java:805)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.revisionInfo(BrowserFetcher.java:757)
	at com.ruiyun.jvppeteer.launch.ChromeLauncher.resolveExecutablePath(ChromeLauncher.java:206)
	at com.ruiyun.jvppeteer.launch.ChromeLauncher.launch(ChromeLauncher.java:82)
	at com.ruiyun.jvppeteer.core.Puppeteer.rawLaunch(Puppeteer.java:111)
	at com.ruiyun.jvppeteer.core.Puppeteer.launch(Puppeteer.java:70)

![image](https://user-images.githubusercontent.com/25025928/94126214-ebe74b80-fe89-11ea-90e6-14dda6b12c0e.png)

**Comment by fanyong920** [comment]
确实是的。


目前你可以指定一下启动路径 withExecuXXXXpath(),或者启动前BrowserFetcher.downloadIfNotExist(null)先下载一下。


那个空指针问题，我改了一下，暂时只是提交了代码。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fanyong920/jvppeteer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月24日(星期四) 下午5:18
收件人:&nbsp;"fanyong920/jvppeteer"<jvppeteer@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[fanyong920/jvppeteer] 1.0.9版本快速启动报NFE (#19)





 
java.lang.NumberFormatException: null
 at java.lang.Integer.parseInt(Integer.java:542)
 at java.lang.Integer.parseInt(Integer.java:615)
 at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.archiveName(BrowserFetcher.java:805)
 at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.revisionInfo(BrowserFetcher.java:757)
 at com.ruiyun.jvppeteer.launch.ChromeLauncher.resolveExecutablePath(ChromeLauncher.java:206)
 at com.ruiyun.jvppeteer.launch.ChromeLauncher.launch(ChromeLauncher.java:82)
 at com.ruiyun.jvppeteer.core.Puppeteer.rawLaunch(Puppeteer.java:111)
 at com.ruiyun.jvppeteer.core.Puppeteer.launch(Puppeteer.java:70)

**Comment by Burgges** [comment]
好的   我试下
