### ISSUE TITLE
MAC IDEA 启动浏览器失败

### ISSUE THREAD

**Issue by diypyh** [fanyong920/jvppeteer#23]
<img width="1674" alt="WX20201010-141853@2x" src="https://user-images.githubusercontent.com/10149161/95647676-fa796800-0b03-11eb-8a22-4d99f4d24893.png">

**Comment by diypyh** [comment]
14:13:58.941 [main] INFO com.ruiyun.jvppeteer.core.browser.BrowserFetcher - revision:722234，executablePath:/Users/panyh/myProject/.local-browser/mac-722234/chrome-mac/Chromium.app/Contents/MacOS/Chromium，folderPath:/Users/panyh/myProject/.local-browser/mac-722234，local:true，url:https://npm.taobao.org/mirrors/chromium-browser-snapshots/Mac/722234/chrome-mac.zip，product:chrome
14:13:59.272 [WebSocketConnectReadThread-18] ERROR com.ruiyun.jvppeteer.transport.WebSocketTransport - Websocket error:
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.Socket.connect(Socket.java:608)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:461)
	at java.base/java.lang.Thread.run(Thread.java:834)
14:13:59.272 [WebSocketConnectReadThread-18] INFO com.ruiyun.jvppeteer.transport.WebSocketTransport - Connection closed by us Code: -1 Reason: Connection refused (Connection refused)
14:13:59.276 [main] INFO com.ruiyun.jvppeteer.core.browser.BrowserRunner - Connect to browser by websocket url: ws://127.0.0.1:56570/devtools/browser/c196484b-dcdd-4a52-8f2b-b4e72eed4901
Exception in thread "main" org.java_websocket.exceptions.WebsocketNotConnectedException
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:628)
	at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:605)
	at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:410)
	at com.ruiyun.jvppeteer.transport.Connection.rawSend(Connection.java:132)
	at com.ruiyun.jvppeteer.transport.Connection.send(Connection.java:75)
	at com.ruiyun.jvppeteer.core.browser.Browser.create(Browser.java:229)
	at com.ruiyun.jvppeteer.launch.ChromeLauncher.launch(ChromeLauncher.java:94)
	at com.ruiyun.jvppeteer.core.Puppeteer.rawLaunch(Puppeteer.java:111)
	at com.ruiyun.jvppeteer.core.Puppeteer.launch(Puppeteer.java:70)
	at com.panyh.reptile.jvppeteer.CookieTest.main(CookieTest.java:34)
Disconnected from the target VM, address: '127.0.0.1:56479', transport: 'socket'

**Comment by fanyong920** [comment]
看看我指定的一个issue。我暂时还没解决这mac安装chrome的问题，因为我没有mac。。。
有一个办法就是你使用自己已有的chrome路径

**Comment by diypyh** [comment]
> 看看我指定的一个issue。我暂时还没解决这mac安装chrome的问题，因为我没有mac。。。
> 有一个办法就是你使用自己已有的chrome路径

好像没有看到使用指定chrome路径的样例，能写一下看看吗？谢谢

**Comment by bestmemory** [comment]
LaunchOptions options = new LaunchOptionsBuilder()
        .withExecutablePath(
            "/XXXXXXXX/chrome-mac/Chromium.app/Contents/MacOS/Chromium")
        .withArgs(argList).withHeadless(false).build();
XXXXXX替换你的安装地址

**Comment by hehujun** [comment]
是下载的Chromium的问题 可以手动下载之后 指定路径

**Comment by ZhuBoyang** [comment]
mac上可用的chromium在哪里下载，指定路径指定到google chrome.app么
