### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by jiangqiang1996** [fanyong920/jvppeteer#40]
启动报错啊，一直出现下载失败的日志，而且会爆文件被占用。我电脑都重启了，还是这样。

```
[2020-12-21 15:36:20.138][com.ruiyun.jvppeteer.core.browser.BrowserFetcher:764]INFO  -- revision:722234，executablePath:D:\Documents\Code\IdeaProjects\test\.local-browser\win64-722234\chrome-win\chrome.exe，folderPath:D:\Documents\Code\IdeaProjects\test\.local-browser\win64-722234，local:false，url:https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip，product:chrome
[2020-12-21 15:36:20.145][com.ruiyun.jvppeteer.core.browser.BrowserFetcher:703]INFO  -- Downloading binary from https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip
[2020-12-21 15:36:22.378][com.ruiyun.jvppeteer.util.DownloadUtil:221]ERROR -- download url[https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip] bytes[bytes=15728640-20971520] fail.
[2020-12-21 15:36:22.380][com.ruiyun.jvppeteer.util.DownloadUtil:221]ERROR -- download url[https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip] bytes[bytes=20971520-26214400] fail.
[2020-12-21 15:36:22.376][com.ruiyun.jvppeteer.util.DownloadUtil:221]ERROR -- download url[https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip] bytes[bytes=10485760-15728640] fail.
[2020-12-21 15:36:22.492][com.ruiyun.jvppeteer.util.DownloadUtil:221]ERROR -- download url[https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip] bytes[bytes=0-5242880] fail.
[2020-12-21 15:36:22.493][com.ruiyun.jvppeteer.util.DownloadUtil:100]ERROR -- download fail,url:https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip
Exception in thread "main" java.nio.file.FileSystemException: D:\Documents\Code\IdeaProjects\test\.local-browser\chrome-win.zip: 另一个程序正在使用此文件，进程无法访问。

	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:270)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1180)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.unlinkAsync(BrowserFetcher.java:462)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.download(BrowserFetcher.java:238)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.download(BrowserFetcher.java:263)
	at com.ruiyun.jvppeteer.core.browser.BrowserFetcher.downloadIfNotExist(BrowserFetcher.java:159)
	at xin.jiangqiang.test.puppeteer.Test2.main(Test2.java:21)
[2020-12-21 15:36:23.132][com.ruiyun.jvppeteer.util.DownloadUtil:221]ERROR -- download url[https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip] bytes[bytes=41943040-47185920] fail.
[2020-12-21 15:36:23.922][com.ruiyun.jvppeteer.util.DownloadUtil:221]ERROR -- download url[https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip] bytes[bytes=47185920-52428800] fail.
[2020-12-21 15:36:27.467][com.ruiyun.jvppeteer.util.DownloadUtil:221]ERROR -- download url[https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip] bytes[bytes=62914560-68157440] fail.
[2020-12-21 15:36:28.427][com.ruiyun.jvppeteer.util.DownloadUtil:221]ERROR -- download url[https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip] bytes[bytes=78643200-83886080] fail.
[2020-12-21 15:36:29.803][com.ruiyun.jvppeteer.util.DownloadUtil:221]ERROR -- download url[https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip] bytes[bytes=89128960-94371840] fail.
[2020-12-21 15:36:29.810][com.ruiyun.jvppeteer.util.DownloadUtil:221]ERROR -- download url[https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip] bytes[bytes=94371840-99614720] fail.
[2020-12-21 15:36:31.331][com.ruiyun.jvppeteer.util.DownloadUtil:221]ERROR -- download url[https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip] bytes[bytes=110100480-115343360] fail.
[2020-12-21 15:36:31.447][com.ruiyun.jvppeteer.util.DownloadUtil:221]ERROR -- download url[https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip] bytes[bytes=115343360-120586240] fail.
[2020-12-21 15:36:34.010][com.ruiyun.jvppeteer.util.DownloadUtil:221]ERROR -- download url[https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/722234/chrome-win.zip] bytes[bytes=131072000-136314880] fail.

Process finished with exit code 1

```

**Comment by liuhulu** [comment]
后来问题解决了么？我也一直有这个问题。

**Comment by liuhulu** [comment]
我发现是jdk问题，我使用jdk8没有这个问题了，但是用openjdk11还是有问题。
@fanyong920

**Comment by jiangqiang2020** [comment]
> 我发现是jdk问题，我使用jdk8没有这个问题了，但是用openjdk11还是有问题。
> @fanyong920

我直接用的jdk11 会报错
