### ISSUE TITLE
demo PageExposeFunctionExample.java ，exposeFunction函数调用异常 

### ISSUE THREAD

**Issue by 597901544** [fanyong920/jvppeteer#42]
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.RuntimeException: com.ruiyun.jvppeteer.exception.ProtocolException: Protocol error : "Given expression does not evaluate to a function"
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.ruiyun.jvppeteer.core.page.Page.exposeFunction(Page.java:1535)
	at com.ruiyun.example.PageExposeFunctionExample.main(PageExposeFunctionExample.java:28)
Caused by: java.lang.RuntimeException: com.ruiyun.jvppeteer.exception.ProtocolException: Protocol error : "Given expression does not evaluate to a function"
	at com.ruiyun.jvppeteer.core.page.ExecutionContext.evaluateInternal(ExecutionContext.java:119)
	at com.ruiyun.jvppeteer.core.page.ExecutionContext.evaluate(ExecutionContext.java:69)
	at com.ruiyun.jvppeteer.core.page.DOMWorld.evaluate(DOMWorld.java:134)
	at com.ruiyun.jvppeteer.core.page.Frame.evaluate(Frame.java:98)
	at com.ruiyun.jvppeteer.core.page.Page.lambda$null$6(Page.java:1533)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.ruiyun.jvppeteer.exception.ProtocolException: Protocol error : "Given expression does not evaluate to a function"
	at com.ruiyun.jvppeteer.transport.CDPSession.send(CDPSession.java:140)
	at com.ruiyun.jvppeteer.core.page.ExecutionContext.evaluateInternal(ExecutionContext.java:114)
	... 10 more

**Comment by anyflywen** [comment]
可以看我的dev分支修复了这个问题
