### ISSUE TITLE
Page.waitForSelector() method can't work

### ISSUE THREAD

**Issue by rqh656418510** [fanyong920/jvppeteer#5]
``` java
    @Test
    public void waitForSelector() throws IOException, InterruptedException, ExecutionException {
        String path = "/usr/bin/google-chrome-stable";
        ArrayList<String> arrayList = new ArrayList<>();
        LaunchOptions options = new OptionsBuilder().withArgs(arrayList).withHeadless(false).withExecutablePath(path).build();
        arrayList.add("--no-sandbox");
        arrayList.add("--disable-setuid-sandbox");

        WaitForSelectorOptions selectorOptions = new WaitForSelectorOptions();
        selectorOptions.setVisible(true);
        selectorOptions.setHidden(false);
        selectorOptions.setTimeout(60000);

        Browser browser = Puppeteer.launch(options);
        Page page = browser.newPage();
        page.goTo("https://blog.csdn.net/pythonw/article/details/80263428");

        String ex_string = "#mainBox > main > div.template-box > span:nth-child(3)";
        page.waitForSelector(ex_string, selectorOptions);
        page.hover(ex_string);
        System.in.read();
    }
```

```
java.lang.NullPointerException
	at com.ruiyun.jvppeteer.core.page.DOMWorld.waitForSelectorOrXPath(DOMWorld.java:423)
	at com.ruiyun.jvppeteer.core.page.DOMWorld.waitForSelector(DOMWorld.java:376)
	at com.ruiyun.jvppeteer.core.page.Frame.waitForSelector(Frame.java:176)
	at com.ruiyun.jvppeteer.core.page.Page.waitForSelector(Page.java:1894)
	at com.jvppeteer.example.Test.waitForSelector(Test.java:40)
```

**Comment by fanyong920** [comment]
thanks for Test
我找到了问题所在。是因为WaitTask类存在缺陷。现在已经修复
![image](https://user-images.githubusercontent.com/45630410/83318707-d1012380-a269-11ea-9b90-9659a3a39b26.png)
麻烦重新测试一下

**Comment by rqh656418510** [comment]
thanks, it can work normally!
