### ISSUE TITLE
截全屏报错

### ISSUE THREAD

**Issue by 200841113** [fanyong920/jvppeteer#59]
Exception in thread "main" com.ruiyun.jvppeteer.exception.ProtocolException: Protocol error : "Invalid parameters" "width: integer value expected; height: integer value expected"
	at com.ruiyun.jvppeteer.transport.CDPSession.send(CDPSession.java:140)
	at com.ruiyun.jvppeteer.core.page.Page.screenshotTask(Page.java:1036)
	at com.ruiyun.jvppeteer.core.page.Page.lambda$screenshot$0(Page.java:776)
	at com.ruiyun.jvppeteer.core.page.TaskQueue.postTask(TaskQueue.java:17)
	at com.ruiyun.jvppeteer.core.page.Page.screenshot(Page.java:774)
	at com.xes.master.data.open.spider.controller.TestController.main(TestController.java:40)

**Comment by 200841113** [comment]
ArrayList<String> arrayList = new ArrayList<>();
        LaunchOptions options = new LaunchOptionsBuilder().withExecutablePath("/Users/xes/Documents/software/chrome-mac/Chromium.app/Contents/MacOS/Chromium").withArgs(arrayList).withHeadless(true).build();
        arrayList.add("--no-sandbox");
        arrayList.add("--disable-setuid-sandbox");
        Browser browser = Puppeteer.launch(options);
        Page page = browser.newPage();
//        PageNavigateOptions navigateOptions = new PageNavigateOptions();
//        navigateOptions.setWaitUntil(Arrays.asList("domcontentloaded"));
//        page.goTo("http://www.baidu.com", navigateOptions);
        page.goTo("http://www.baidu.com");
        ScreenshotOptions screenshotOptions = new ScreenshotOptions();

        //page.setViewport(new Viewport(1080,1920,1,false,false,true));
        //设置截图范围
//        Clip clip = new Clip(1.0,1.56,400,400);
//        screenshotOptions.setClip(clip);
        screenshotOptions.setFullPage(Boolean.TRUE);
        //设置存放的路径
        screenshotOptions.setPath("/Users/xes/Desktop/test.png");
        screenshotOptions.setType("png");
        page.screenshot(screenshotOptions);

**Comment by MaxBill** [comment]
设置截图范围应该用Clip
